adamchainz/time-machine

src/time_machine.py
tests/test_time_machine.py

These use time-based functions to generate UUID's, which include the time of generation. So they also need patching.
Copied from freezegun where it was added in https://github.com/spulec/freezegun/pull/172 .

💐 Patch UUID generation functions

---

.github/workflows/main.yml
setup.cfg

It's linked prominently through project_urls already, it doesn't need to pollute the PyPI display of the README. Additionally it's sometimes necessary to push a change for a past release, but such changes cannot be added to that release's PyPI description as it's immutable.

Stop including changelog in PyPI description

---

HISTORY.rst
README.rst
src/time_machine.py
tests/test_time_machine.py

Add shift() method

---

.github/workflows/main.yml
HISTORY.rst
src/_time_machine.c
src/time_machine.py
tests/test_time_machine.py

Python in macos has a couple of challenges to be overcome:
CLOCK_REALTIME and clock_gettime are not present. The python docs list it as available in Unix environments, but this doesn't seem to include macos:
https://docs.python.org/3/library/time.html#time.CLOCK_REALTIME
https://news.ycombinator.com/item?id=6303755

Fix to work when clock_gettime or CLOCK_REALTIME are not present

---

HISTORY.rst
src/_time_machine.c

Fixes #36.
Tested by building wheel locally with pyenv Python and installing and using it on Python.org Python.

Move C-level clock_gettime() and clock_gettime_ns() checks to runtime

---

src/time_machine.py
tests/test_time_machine.py

Contributes towards https://github.com/adamchainz/time-machine/issues/20

Implement `move_to`

---

HISTORY.rst
src/time_machine.py
tests/test_time_machine.py

Return naive datetimes from mocked datetime.utcnow()

---

README.rst

Windows doesn’t like travelling back beyond 1970, because computers.

Replace travelled-to time in examples

---

HISTORY.rst
README.rst
src/time_machine.py
tests/test_time_machine.py

Rather than try fix `tz_offset`, remove it and replace it with complete timezone mocking, after deliberation in #65 .

Mock timezone when destination has a ZoneInfo timezone

---

HISTORY.rst
src/time_machine.py
tests/test_time_machine.py

Work with Windows’ different epoch

---

.github/workflows/build.yml
HISTORY.rst

* Pin OS versions
* build for multiple linux architectures - fixes #110
* Don't install Visual C++ for Python 2.7 on windows - we aren't using Python 2.7, don't know how this would have been useful?

Update wheel building

---

src/_time_machine.c

Realized #137 accidentally didn't decrease refs after the `PyImport_ImportModule` calls.

Fix refcounts for imported modules

---

pyproject.toml
src/time_machine/__init__.py

For whatever reason isort on pre-commit.ci is picking up _time_machine as third party, whilst locally it's not. To stabilize import sorting, declare it as always first party.

Fix isort config

---

.github/workflows/build.yml

They're only needed on the main branch during release. Building them on every PR is safe but wastes a lot of time.

Stop building wheels on PR's

---

README.rst

Django's module is called `timezone`, not `time`.
I got confused when reading the README (on PyPI) and thought there was a new module in Django that I hadn't heard about.
Thanks! ✨

[minor] Fix name of Django module in README

---

.github/workflows/build.yml

Use the correct version specifier to build wheels on Python 3.11 (`cp310-*` was specified instead of `cp311-*`).

fix: build wheels for Python 3.11

---

HISTORY.rst
src/time_machine/__init__.py

Tested with this example file:
```
import time_machine
from unittest import TestCase
@time_machine.travel(1)
def f() -> int:
return 123
reveal_type(f)
@time_machine.travel(1)
async def g() -> int:
return 123
reveal_type(g)
@time_machine.travel(1)
class MyTests(TestCase):
xxx: int
reveal_type(MyTests)
reveal_type(MyTests.xxx)
```
Before the `reveal_types` would only show generic types, now they show the original signatures.

Improve travel() type hints to preserve wrapped type

---

.pre-commit-config.yaml
pyproject.toml
setup.py
src/time_machine/__init__.py
tests/test_time_machine.py

It’s [way faster](https://twitter.com/codewithanthony/status/1553034384206438401) and its one-import-per-line style prevents merge conflicts.

Move from isort to reorder-python-imports

---

setup.py

Since PyPy is currently unsupported, throw an explicit error when one attempts to build time-machine.  This should prevent packages from trying to use time-machine which can cause segfaults at runtime.
See issue #305

Throw an explicit error when trying to build on PyPy

---

.github/workflows/build.yml
CHANGELOG.rst

Thanks to new cibuildwheel: https://github.com/pypa/cibuildwheel/releases/tag/v2.15.0

Build wheels for Python 3.12

---

CHANGELOG.rst
README.rst
src/time_machine/__init__.py
tests/test_time_machine.py

Addresses feature request #247: adds `shift(delta)` to pytest fixture.

Add `shift()` method to `time_machine` pytest fixture

---

CHANGELOG.rst
README.rst
src/time_machine/__init__.py
tests/test_time_machine.py

Adds support to pass a datetime.timedelta object to `travel`.
To avoid potential abuse this feature is blocked when already traveling, since the `shift` API would provide similar functionality and should be simpler.
This should open an API to implement #247
fixes #38

Add support for dt.timedelta to travel class

---

CHANGELOG.rst
README.rst
tests/test_time_machine.py

Addresses the documentation issue raised in #257:
passing a naive date string to `travel` will be interpreted as local time

Fix docs on timezone of naive date(time) strings

---

tests/test_time_machine.py

Tidy tests to use change_local_timezone()

---

tests/test_time_machine.py

On platforms without a high-resolution clock, such as Alpha and PA-RISC is is likely that two sequential calls to time.time() will return the same value if the execution time is not sufficient to allow one full clock resolution cycle to pass.  This adds sleeps of one cycle to enforce that the minimum amount of time to guarantee a clock change has passed.
On systems with high-resolution clocks, clock_getres() will return 1ns; in reality the sleep will take longer than 1ns to execute but should still be a negligible amount of time.
Downstream bug report with test logs:  https://bugs.gentoo.org/912709

Fix tests on platforms with low clock resolution

---

CHANGELOG.rst
src/time_machine/__init__.py
tox.ini

In python 3.12 the following DeprecationWarning appears:
```
/time_machine/__init__.py:354: DeprecationWarning: datetime.datetime.utcfromtimestamp() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.fromtimestamp(timestamp, datetime.UTC).
```
This commit fixes it and also removes the suppression from `tox.ini`

Fix utcfromtimestamp() deprecation warning

---

CHANGELOG.rst
src/time_machine/__init__.py
tests/test_time_machine.py

Is related to #402 
The problem is reproduced when setUpClass calls another method: `cls` in this case is of base class type.

Fix class decorator for classmethod overrides

---

CHANGELOG.rst
src/time_machine/__init__.py
tests/test_time_machine.py

Fix timedelta segmentation fault

---

CHANGELOG.rst
src/_time_machine.c

Fixes #456.
The relevant crash from the test log actually seems to be the initial failure:
```
AttributeError: module 'time' has no attribute 'clock_gettime_ns'
The above exception was the direct cause of the following exception:
...
>       _time_machine.patch_if_needed()
E       SystemError: <built-in function patch_if_needed> returned a result with an exception set
```
`PyObject_GetAttrString` fails to get `clock_gettime` and `clock_gettime_ns` on Windows because they only exist on Unix. It returns `NULL` and each time sets the `AttributeError` as the current error. `patch_if_needed` did not clear this, leading to Python's call check to raise a `SystemError` caused by the `AttributeError`, making time-machine fail to start travelling.
I'm not sure which exact change in Python made this …

Fix System Error on Python 3.13 and Windows

---

.github/workflows/build.yml
CHANGELOG.rst

Also upgrade wheel build env:
* GitHub actions images: https://github.com/actions/runner-images
* Python
* cibuildwheel: https://github.com/pypa/cibuildwheel/releases/tag/v2.20.0

Build wheels for Python 3.13

---

.github/workflows/build.yml

PR #467 broke the build due to this bug: https://github.com/pypa/cibuildwheel/issues/1957 .
This time I’ll test the workflow *before* merging.

Downgrade wheel build environment Ubuntu version

---

.github/workflows/build.yml

I noticed the `-*-*` in the CIBW_BUILD for 3.12. Perhaps this could fix the missing wheels 3.12? 
Fixes #469.

Fix CIBW_BUILD argument for Python 3.12

---

.github/workflows/build.yml

Stop building Python 3.7 wheels

---

.github/workflows/main.yml
docs/changelog.rst
docs/installation.rst
pyproject.toml
tox.ini

Looks good!
Had to remove the `uv pip install --system` because i kept getting this error in the threaded python versions:
```
error: The interpreter at /usr is externally managed, and indicates the following:
To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.12/README.venv for …
```

Support free-threaded Python

---

src/_time_machine.c
tests/test_time_machine.py

Without this handling of `NULL`, such errors become segmentation faults.

Propagate errors from 'original' C functions

---

docs/changelog.rst
docs/pytest_plugin.rst
pyproject.toml
src/time_machine/__init__.py
tests/test_time_machine.py

This patch fixes a very niche scenario:
1. When you have a fixture that depends on time.
2. When you need to modify the time before the test is executed.
3. AND be able to change the time while inside the test
```python
import time
@pytest.fixture
def current_time():
return time.time()
def test_normal(current_time):
assert current_time > 1742943111.0
@pytest.mark.time_machine("2000-01-01")
def test_mod(current_time, time_machine):
assert current_time == 946684800.0
time_machine.shift(1)
assert current_time == 946684800.0
assert int(time.time()) == 946684801
```
---
Currently, the code fails:
```
@time_machine.travel("2000-01-01")
def test_mod(current_time, time_machine):
>       assert current_time == 946684800.0
E       assert 1742944978.9803169 == 946684800.0
```
If we ignore the …

Add marker support to pytest plugin
